export enum StableMemoryId {
    AUTHENTICATION,
    MATERIALS,
    PRODUCT_CATEGORIES,
    ORDERS,
    SHIPMENTS,
    COMPANY_CERTIFICATES,
    SCOPE_CERTIFICATES,
    MATERIAL_CERTIFICATES,
    ALL_CERTIFICATE_RECORDS,
    FIAT_ENUM,
    PROCESS_TYPE_ENUM,
    UNIT_ENUM,
    ASSESSMENT_STANDARD_ENUM,
    ASSESSMENT_ASSURANCE_LEVEL_ENUM
}
