export enum StableMemoryId {
    MATERIALS = 0,
    PRODUCT_CATEGORIES = 1,
    ORDERS = 2,
    SHIPMENTS = 3,
    COMPANY_CERTIFICATES = 4,
    SCOPE_CERTIFICATES = 5,
    MATERIAL_CERTIFICATES = 6,
    ALL_CERTIFICATE_RECORDS = 7,
    FIAT_ENUM = 8,
    PROCESS_TYPE_ENUM = 9,
    UNIT_ENUM = 10,
    ASSESSMENT_STANDARD_ENUM = 11,
    ASSESSMENT_ASSURANCE_LEVEL_ENUM = 12
}
