export enum StableMemoryId {
    MATERIALS = 0,
    PRODUCT_CATEGORIES = 1,
    ORDERS = 2,
    SHIPMENTS = 3,
    COMPANY_CERTIFICATES = 4,
    SCOPE_CERTIFICATES = 5,
    MATERIAL_CERTIFICATES = 6,
    ALL_CERTIFICATE_RECORDS = 7,
    ENUMERATIONS = 8
}
