stages:
  - build
  - test
  - deploy

image: node:20

# VARIABLES

variables:
  CI_SCRIPTS: "$CI_PROJECT_DIR/ci/scripts"
  ICP_PATH: "$CI_PROJECT_DIR/icp"
  BUILD_TYPES_PATH: "$ICP_PATH/ts-canisters/src/models/types/dist/"
  TYPESCRIPT_NODE_MODULES_PATH: "$ICP_PATH/ts-canisters/node_modules/"
  ICP_DECLARATIONS_PATH: "$ICP_PATH/ts-canisters/declarations/"
  ICP_RUST_DECLARATIONS_PATH: "$ICP_PATH/rust-canisters/src/declarations/"
  ICP_RUST_WASM_PATH: "$ICP_PATH/rust-canisters/target/wasm32-unknown-unknown/release/"
  DFX_INSTALLATION_PATH: "/root/.local/share/dfx/bin"
  CARGO_INSTALLATION_PATH: "/root/.cargo/bin"

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - "$TYPESCRIPT_NODE_MODULES_PATH"
  policy: pull-push

# RULES

.rules_dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always

.rules_force_deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == "force-deploy"
      when: always

# TEMPLATE JOBS

.build_job_template:
  stage: build
#  rules:
#    - !reference [ .rules_dev, rules ]
#    - !reference [ .rules_force_deploy, rules ]

.test_job_template:
  stage: test
#  rules:
#    - !reference [ .rules_dev, rules ]

.deploy_job_template:
  stage: deploy
#  rules:
#    - !reference [ .rules_dev, rules ]
#    - !reference [ .rules_force_deploy, rules ]

# JOBS

before_script:
  - cd $CI_SCRIPTS
  - chmod +x install-dependencies.sh
  - ./install-dependencies.sh
  - export PATH=$PATH:$DFX_INSTALLATION_PATH:$CARGO_INSTALLATION_PATH

#build_icp_canisters_job:
#  extends: .build_job_template
#  script:
#    - cd $ICP_PATH/ts-canisters
#    - npm ci
#    - cd ../scripts
#    - chmod +x build-canisters.sh
#    - ./build-canisters.sh
#  artifacts:
#    paths:
#      - $BUILD_TYPES_PATH
#      - $ICP_DECLARATIONS_PATH
#      - $ICP_RUST_DECLARATIONS_PATH
#      - $ICP_RUST_WASM_PATH
#    expire_in: 15 min

deploy_icp_canisters_job:
  extends: .deploy_job_template
  script:
    - cd $ICP_PATH/ts-canisters
#    - npm ci
    - cd ../scripts
    - chmod +x import-identity-ic.sh deploy-ic.sh
    - ./import-identity-ic.sh
#    - ./deploy-ic.sh
#  when: manual