version: '3.8'

services:
  blockchain_node:
    container_name: blockchain_node
    build:
      context: ./blockchain
      dockerfile: docker/blockchain/BlockchainDockerfile
      args:
        BLOCKCHAIN_LIB_REGISTRY_DOMAIN: ${BLOCKCHAIN_LIB_REGISTRY_DOMAIN}
        BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN: ${BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN}
    environment:
      SUPPLIER_ADMIN: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
      CUSTOMER_ADMIN: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    ports:
      - "8545:8545"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --header=\"Content-Type: application/json\" --post-data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' -O - http://localhost:8545" ]
      interval: 5s
      timeout: 5s
      retries: 30

  blockchain_contract_deployer:
    container_name: blockchain_contract_deployer
    depends_on:
      blockchain_node:
        condition: service_healthy
    build:
      context: ./blockchain
      dockerfile: docker/blockchain/BlockchainDockerfile
      args:
        BLOCKCHAIN_LIB_REGISTRY_DOMAIN: ${BLOCKCHAIN_LIB_REGISTRY_DOMAIN}
        BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN: ${BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN}
    entrypoint: sh -c "npx hardhat run scripts/deploy.ts --network testnet"
    environment:
      SUPPLIER_ADMIN: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
      CUSTOMER_ADMIN: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
      RPC_URL: "http://blockchain_node:8545/"
      PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
#  package_lib:
#    build:
#      context: ./apis/bc-sync
#      dockerfile: ../../docker/bc-sync/BCSyncBackendDockerfile
#      args:
#        BLOCKCHAIN_LIB_REGISTRY_DOMAIN: ${BLOCKCHAIN_LIB_REGISTRY_DOMAIN}
#        BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN: ${BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN}
#        COFFEE_TRADING_LIB_REGISTRY_DOMAIN: ${COFFEE_TRADING_LIB_REGISTRY_DOMAIN}
#        COFFEE_TRADING_LIB_REGISTRY_READ_TOKEN: ${COFFEE_TRADING_LIB_REGISTRY_READ_TOKEN}
#    container_name: bc-sync-api
#    restart: always
#    depends_on:
#      - unece_mysql
#    ports:
#      - "8090:8090"


