version: '3.8'

services:
  blockchain_node:
    container_name: blockchain_node
    image: gitlab-core.supsi.ch:5050/dti-isin/giuliano.gremlich/blockchain/one-lib-to-rule-them-all/coffe-trading-management/blockchain-node
    ports:
      - "8545:8545"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --header=\"Content-Type: application/json\" --post-data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' -O - http://localhost:8545" ]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - bc_proxy_net

  blockchain_contract_deployer:
    container_name: blockchain_contract_deployer
    depends_on:
      blockchain_node:
        condition: service_healthy
    image: gitlab-core.supsi.ch:5050/dti-isin/giuliano.gremlich/blockchain/one-lib-to-rule-them-all/coffe-trading-management/blockchain-node
    entrypoint: sh -c "NODE_ENV=test npx hardhat run scripts/deploy.ts --network testnet"
    environment:
      SUPPLIER_ADMIN: ${SUPPLIER_ADMIN}
      CUSTOMER_ADMIN: ${CUSTOMER_ADMIN}
      COMMISSIONER_ADMIN: ${COMMISSIONER_ADMIN}
      RPC_URL: "http://blockchain_node:8545/"
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - bc_proxy_net

networks:
  bc_proxy_net:
    name: bc-coffee-net
