export enum Enumeration {
    FIAT = 'FIAT',
    UNIT = 'UNIT',
    PROCESS_TYPE = 'PROCESS_TYPE',
    ASSESSMENT_STANDARD = 'ASSESSMENT_STANDARD',
    ASSESSMENT_ASSURANCE_LEVEL = 'ASSESSMENT_ASSURANCE_LEVEL'
}
