[package]
name = "c2c_permission"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
shared_types = {path = "../../libraries/shared_types" }
